<?php
declare(strict_types=1);

session_start();
set_time_limit(0);

$root = __DIR__;
$envPath = $root . DIRECTORY_SEPARATOR . '.env';
$lockPath = $root . DIRECTORY_SEPARATOR . '.endless-installed';

function e(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function random_secret(int $bytes = 32): string
{
    return bin2hex(random_bytes($bytes));
}

function bool_value(string $key): bool
{
    return isset($_POST[$key]) && $_POST[$key] === '1';
}

function post_value(string $key, string $default = ''): string
{
    return trim((string)($_POST[$key] ?? $default));
}

function build_database_url(string $host, string $port, string $database, string $user, string $password, string $schema): string
{
    $auth = rawurlencode($user) . ':' . rawurlencode($password);
    $path = rawurlencode($database);
    $query = rawurlencode($schema ?: 'public');
    return "postgresql://{$auth}@{$host}:{$port}/{$path}?schema={$query}";
}

function write_env_file(string $path, array $values): void
{
    $lines = [
        '# Generated by Endless installer',
        'DATABASE_URL="' . addcslashes($values['DATABASE_URL'], "\\\"") . '"',
        'NEXT_PUBLIC_SITE_URL="' . addcslashes($values['NEXT_PUBLIC_SITE_URL'], "\\\"") . '"',
        'AI_CREDENTIALS_SECRET="' . addcslashes($values['AI_CREDENTIALS_SECRET'], "\\\"") . '"',
        'STUDIO_OWNER_EMAIL="' . addcslashes($values['STUDIO_OWNER_EMAIL'], "\\\"") . '"',
        'STUDIO_OWNER_PASSWORD="' . addcslashes($values['STUDIO_OWNER_PASSWORD'], "\\\"") . '"',
        'STUDIO_SESSION_SECRET="' . addcslashes($values['STUDIO_SESSION_SECRET'], "\\\"") . '"',
        ''
    ];

    if (file_put_contents($path, implode(PHP_EOL, $lines), LOCK_EX) === false) {
        throw new RuntimeException('Unable to write .env. Please check directory permissions.');
    }
}

function run_command(string $command, string $cwd): array
{
    if (!function_exists('proc_open')) {
        return ['code' => 127, 'output' => 'proc_open is disabled in PHP.'];
    }

    $descriptorSpec = [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w']
    ];

    $process = proc_open($command, $descriptorSpec, $pipes, $cwd);
    if (!is_resource($process)) {
        return ['code' => 1, 'output' => "Unable to start command: {$command}"];
    }

    fclose($pipes[0]);
    $output = stream_get_contents($pipes[1]) ?: '';
    $error = stream_get_contents($pipes[2]) ?: '';
    fclose($pipes[1]);
    fclose($pipes[2]);
    $code = proc_close($process);

    return [
        'code' => $code,
        'output' => trim($output . PHP_EOL . $error)
    ];
}

function command_exists(string $binary): bool
{
    $result = run_command('command -v ' . escapeshellarg($binary), __DIR__);
    return $result['code'] === 0;
}

function default_site_url(): string
{
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = (string)($_SERVER['HTTP_HOST'] ?? 'localhost:3000');
    return "{$scheme}://{$host}";
}

function installer_locked(string $lockPath): bool
{
    return is_file($lockPath) && ($_GET['unlock'] ?? '') !== '1';
}

if (empty($_SESSION['endless_installer_token'])) {
    $_SESSION['endless_installer_token'] = random_secret(16);
}

$token = (string)$_SESSION['endless_installer_token'];
$installed = installer_locked($lockPath);
$messages = [];
$errors = [];
$logs = [];

$defaults = [
    'site_url' => default_site_url(),
    'db_host' => '127.0.0.1',
    'db_port' => '5432',
    'db_name' => 'endless',
    'db_user' => 'endless',
    'db_schema' => 'public',
    'studio_email' => 'owner@endless.local',
    'node_path' => '/root/.hermes/node/bin:/usr/local/bin:/usr/bin:/bin',
    'pm2_name' => 'endless-cms',
    'app_port' => '3000'
];

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$installed) {
    try {
        if (!hash_equals($token, (string)($_POST['_token'] ?? ''))) {
            throw new RuntimeException('Installer session expired. Refresh this page and try again.');
        }

        $siteUrl = post_value('site_url', $defaults['site_url']);
        $dbHost = post_value('db_host', $defaults['db_host']);
        $dbPort = post_value('db_port', $defaults['db_port']);
        $dbName = post_value('db_name', $defaults['db_name']);
        $dbUser = post_value('db_user', $defaults['db_user']);
        $dbPassword = (string)($_POST['db_password'] ?? '');
        $dbSchema = post_value('db_schema', $defaults['db_schema']);
        $studioEmail = post_value('studio_email', $defaults['studio_email']);
        $studioPassword = (string)($_POST['studio_password'] ?? '');
        $nodePath = post_value('node_path', $defaults['node_path']);
        $pm2Name = post_value('pm2_name', $defaults['pm2_name']);
        $appPort = post_value('app_port', $defaults['app_port']);

        if (!filter_var($siteUrl, FILTER_VALIDATE_URL)) {
            throw new RuntimeException('Site URL is invalid.');
        }
        if ($dbHost === '' || $dbPort === '' || $dbName === '' || $dbUser === '') {
            throw new RuntimeException('Database host, port, name, and user are required.');
        }
        if ($studioPassword === '') {
            throw new RuntimeException('Studio password is required for a public deployment.');
        }

        $databaseUrl = build_database_url($dbHost, $dbPort, $dbName, $dbUser, $dbPassword, $dbSchema);
        write_env_file($envPath, [
            'DATABASE_URL' => $databaseUrl,
            'NEXT_PUBLIC_SITE_URL' => rtrim($siteUrl, '/'),
            'AI_CREDENTIALS_SECRET' => random_secret(32),
            'STUDIO_OWNER_EMAIL' => $studioEmail,
            'STUDIO_OWNER_PASSWORD' => $studioPassword,
            'STUDIO_SESSION_SECRET' => random_secret(32)
        ]);
        $messages[] = '.env has been written.';

        $pathPrefix = $nodePath !== '' ? 'PATH=' . escapeshellarg($nodePath) . ' ' : '';
        $commands = [];
        if (bool_value('run_install')) {
            $commands[] = $pathPrefix . 'pnpm install --frozen-lockfile';
        }
        if (bool_value('run_generate')) {
            $commands[] = $pathPrefix . 'pnpm db:generate';
        }
        if (bool_value('run_push')) {
            $commands[] = $pathPrefix . 'pnpm db:push';
        }
        if (bool_value('run_seed')) {
            $commands[] = $pathPrefix . 'pnpm db:seed';
        }
        if (bool_value('run_build')) {
            $commands[] = $pathPrefix . 'pnpm build';
        }
        if (bool_value('run_pm2')) {
            $safeName = escapeshellarg($pm2Name ?: 'endless-cms');
            $safePort = escapeshellarg($appPort ?: '3000');
            $commands[] = $pathPrefix . "PORT={$safePort} pm2 restart {$safeName} --update-env || PORT={$safePort} pm2 start pnpm --name {$safeName} -- start";
        }

        foreach ($commands as $command) {
            $logs[] = '$ ' . $command;
            $result = run_command($command, $root);
            $logs[] = $result['output'] !== '' ? $result['output'] : '(no output)';
            if ($result['code'] !== 0) {
                throw new RuntimeException("Command failed with exit code {$result['code']}: {$command}");
            }
        }

        file_put_contents($lockPath, 'Installed at ' . date(DATE_ATOM) . PHP_EOL, LOCK_EX);
        $installed = true;
        $messages[] = 'Endless is installed. Remove install.php after verifying the site.';
    } catch (Throwable $error) {
        $errors[] = $error->getMessage();
    }
}

$checks = [
    'PHP version >= 8.1' => version_compare(PHP_VERSION, '8.1.0', '>='),
    'Writable project root' => is_writable($root),
    'proc_open available' => function_exists('proc_open'),
    'pnpm available to PHP user' => command_exists('pnpm'),
    'pm2 available to PHP user' => command_exists('pm2')
];
?>
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Endless Installer</title>
  <style>
    :root {
      color-scheme: light dark;
      --bg: #f7f3ed;
      --panel: #fffaf3;
      --text: #241f1a;
      --muted: #756a5e;
      --border: rgba(36, 31, 26, .14);
      --accent: #9b4f2f;
      --ok: #1f7a4d;
      --bad: #b42338;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #171310;
        --panel: #211b16;
        --text: #f4eee6;
        --muted: #b7aa9d;
        --border: rgba(244, 238, 230, .16);
        --accent: #e29b72;
      }
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.55;
    }
    main {
      width: min(1080px, calc(100vw - 32px));
      margin: 0 auto;
      padding: 48px 0 72px;
    }
    header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 24px;
      margin-bottom: 28px;
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 16px;
      min-width: 0;
    }
    .brand-mark {
      display: grid;
      width: 72px;
      height: 72px;
      flex: 0 0 auto;
      place-items: center;
      border-radius: 20px;
      background: var(--text);
      color: var(--bg);
    }
    .brand-mark svg { width: 42px; height: 42px; }
    .brand-copy {
      display: grid;
      gap: 8px;
      min-width: 0;
    }
    .version-pill {
      border: 1px solid var(--border);
      border-radius: 999px;
      padding: 8px 12px;
      color: var(--muted);
      font-size: .82rem;
      white-space: nowrap;
    }
    h1 {
      margin: 0;
      font-size: clamp(2.35rem, 8vw, 4.85rem);
      line-height: .92;
      letter-spacing: 0;
    }
    h2 { margin: 0 0 14px; font-size: 1.05rem; }
    p { margin: 0; color: var(--muted); }
    .grid { display: grid; gap: 16px; }
    .layout {
      display: grid;
      grid-template-columns: minmax(0, 1fr) 320px;
      gap: 18px;
      align-items: start;
    }
    .panel {
      border: 1px solid var(--border);
      background: var(--panel);
      border-radius: 8px;
      padding: 20px;
    }
    .fields {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 14px;
    }
    label {
      display: grid;
      gap: 6px;
      font-size: .86rem;
      color: var(--muted);
    }
    input {
      width: 100%;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: transparent;
      color: var(--text);
      padding: 10px 11px;
      font: inherit;
      outline: none;
    }
    input:focus { border-color: var(--accent); }
    .checks {
      display: grid;
      gap: 8px;
      margin: 0;
      padding: 0;
      list-style: none;
      font-size: .9rem;
    }
    .checks li {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      border-bottom: 1px solid var(--border);
      padding-bottom: 8px;
    }
    .ok { color: var(--ok); }
    .bad { color: var(--bad); }
    .toggles {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 10px;
    }
    .toggle {
      display: flex;
      align-items: center;
      gap: 8px;
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 10px;
      color: var(--text);
    }
    .toggle input { width: auto; }
    button {
      border: 0;
      border-radius: 6px;
      background: var(--text);
      color: var(--bg);
      padding: 12px 16px;
      font: inherit;
      cursor: pointer;
    }
    code, pre {
      border-radius: 6px;
      background: rgba(0, 0, 0, .08);
      color: var(--text);
    }
    code { padding: 2px 5px; }
    pre {
      overflow: auto;
      padding: 14px;
      white-space: pre-wrap;
      font-size: .82rem;
    }
    .notice {
      border-radius: 6px;
      padding: 12px 14px;
      border: 1px solid var(--border);
      background: rgba(155, 79, 47, .08);
    }
    .full { grid-column: 1 / -1; }
    @media (max-width: 860px) {
      header { align-items: flex-start; flex-direction: column; }
      .layout, .fields, .toggles { grid-template-columns: 1fr; }
      main { padding-top: 28px; }
    }
  </style>
</head>
<body>
<main>
  <header>
    <div class="brand">
      <div class="brand-mark" aria-hidden="true">
        <svg viewBox="0 0 96 96" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M28 28h38v8H37v12h26v8H37v12h29v8H28V28Z" fill="currentColor"/>
        </svg>
      </div>
      <div class="brand-copy">
        <p>Endless CMS</p>
        <h1>Install Endless</h1>
        <p>填写数据库和后台账户，即可初始化内容、构建应用并启动服务。</p>
      </div>
    </div>
    <div class="version-pill">Version 1.0</div>
  </header>

  <?php foreach ($messages as $message): ?>
    <div class="notice ok"><?= e($message) ?></div>
  <?php endforeach; ?>
  <?php foreach ($errors as $error): ?>
    <div class="notice bad"><?= e($error) ?></div>
  <?php endforeach; ?>

  <div class="layout">
    <form method="post" class="panel grid">
      <input type="hidden" name="_token" value="<?= e($token) ?>">
      <?php if ($installed): ?>
        <h2>Installed / 已安装</h2>
        <p>安装锁已存在：<code>.endless-installed</code>。请删除 <code>install.php</code> 或保留锁文件防止重复安装。</p>
      <?php else: ?>
        <h2>Database / 数据库</h2>
        <div class="fields">
          <label>Site URL / 站点地址
            <input name="site_url" value="<?= e(post_value('site_url', $defaults['site_url'])) ?>" required>
          </label>
          <label>DB host / 数据库主机
            <input name="db_host" value="<?= e(post_value('db_host', $defaults['db_host'])) ?>" required>
          </label>
          <label>DB port / 端口
            <input name="db_port" value="<?= e(post_value('db_port', $defaults['db_port'])) ?>" required>
          </label>
          <label>DB name / 数据库名
            <input name="db_name" value="<?= e(post_value('db_name', $defaults['db_name'])) ?>" required>
          </label>
          <label>DB user / 用户名
            <input name="db_user" value="<?= e(post_value('db_user', $defaults['db_user'])) ?>" required>
          </label>
          <label>DB password / 密码
            <input name="db_password" type="password" value="<?= e((string)($_POST['db_password'] ?? '')) ?>">
          </label>
          <label>Schema
            <input name="db_schema" value="<?= e(post_value('db_schema', $defaults['db_schema'])) ?>">
          </label>
        </div>

        <h2>Studio / 后台账户</h2>
        <div class="fields">
          <label>Email
            <input name="studio_email" type="email" value="<?= e(post_value('studio_email', $defaults['studio_email'])) ?>" required>
          </label>
          <label>Password
            <input name="studio_password" type="password" value="<?= e((string)($_POST['studio_password'] ?? '')) ?>" required>
          </label>
        </div>

        <h2>Runtime / 运行环境</h2>
        <div class="fields">
          <label>PATH for Node / Node 路径
            <input name="node_path" value="<?= e(post_value('node_path', $defaults['node_path'])) ?>">
          </label>
          <label>App port / 应用端口
            <input name="app_port" value="<?= e(post_value('app_port', $defaults['app_port'])) ?>">
          </label>
          <label>PM2 name / PM2 名称
            <input name="pm2_name" value="<?= e(post_value('pm2_name', $defaults['pm2_name'])) ?>">
          </label>
        </div>

        <h2>Actions / 安装动作</h2>
        <div class="toggles">
          <label class="toggle"><input type="checkbox" name="run_install" value="1" checked> pnpm install</label>
          <label class="toggle"><input type="checkbox" name="run_generate" value="1" checked> prisma generate</label>
          <label class="toggle"><input type="checkbox" name="run_push" value="1" checked> prisma db push</label>
          <label class="toggle"><input type="checkbox" name="run_seed" value="1" checked> seed demo content</label>
          <label class="toggle"><input type="checkbox" name="run_build" value="1" checked> next build</label>
          <label class="toggle"><input type="checkbox" name="run_pm2" value="1" checked> start with PM2</label>
        </div>

        <button type="submit">Install Endless / 安装 Endless</button>
      <?php endif; ?>
    </form>

    <aside class="panel grid">
      <h2>Server checks / 环境检查</h2>
      <ul class="checks">
        <?php foreach ($checks as $label => $passed): ?>
          <li><span><?= e($label) ?></span><strong class="<?= $passed ? 'ok' : 'bad' ?>"><?= $passed ? 'OK' : 'Missing' ?></strong></li>
        <?php endforeach; ?>
      </ul>
      <p>Endless 是 Next.js 应用，PHP 安装器只负责网页式初始化；安装完成后仍需要 Node.js 运行服务，并在宝塔/Nginx 中反代到应用端口。</p>
      <p>如果 PHP 禁用了 <code>proc_open</code>，请用 README 里的命令行部署脚本完成同样步骤。</p>
    </aside>
  </div>

  <?php if ($logs): ?>
    <section class="panel grid" style="margin-top: 18px;">
      <h2>Install log / 安装日志</h2>
      <pre><?= e(implode(PHP_EOL . PHP_EOL, $logs)) ?></pre>
    </section>
  <?php endif; ?>
</main>
</body>
</html>
